stages:
  - test-data
  - test-model
  - test-app
  - coverage
  - deploy

test-data:
  image: python:3.9.18-alpine3.18
  stage: test-data
  only:
    - main
    - development
    - merge_requests
  script:
    - apk update && apk add python3-dev gcc libc-dev 
    - cd app/
    - pip install -r requirements.txt
    - cd tests/
    - pytest .

test-model:
  image: python:3.9.18-alpine3.18
  stage: test-model
  only:
    - main
    - development
    - merge_requests
  script:
    - apk update && apk add python3-dev gcc libc-dev 

test-app:
  image: python:3.9.18-alpine3.18
  stage: test-app
  only:
    - main
    - development
    - merge_requests
  script:
    - apk update && apk add python3-dev gcc libc-dev 
    - cd app/
    - pip install -r requirements.txt
    - python3 test_app.py

coverage:
  image: python:3.9.18-alpine3.18
  stage: coverage
  only:
    - main
    - development
    - merge_requests
  script:
    - apk update && apk add python3-dev gcc libc-dev 
    - pip install coverage
    - cd app/
    - pip install -r requirements.txt
    - coverage run test_app.py
    - cd tests/
    - python3 -m coverage run -m pytest .
    - cd ..
    - coverage combine .coverage tests/.coverage
    - python3 -m coverage report

deploy:
  image: ubuntu:latest
  stage: deploy
  only:
    - main
  before_script:
    - apt-get -yq update  
    - apt-get -yqq install ssh # install ssh package
    - install -m 600 -D /dev/null ~/.ssh/id_rsa # creates an empty file id_rsa with read/write permissions for the owner only
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa # decodes the base64 encoded private key and writes it to the id_rsa file
    - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts # add the host to the list of known hosts
  script:
    - ssh $SSH_USER@$SSH_HOST "rm -rf $WORK_DIR && git clone $CI_REPOSITORY_URL && cd $WORK_DIR && git checkout main && cd app && docker compose up -d --build && exit" # ssh to the host, pull the latest changes, build the docker image and run the container
  after_script:
    - rm -rf ~/.ssh # remove the private key