services:
  recommender:
    build: .
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  nginx:
    container_name: nginx
    build: nginx
    # Bind the port 8082 of container to machine port 8082
    ports:
      - 8082:8082
    # Make app as nginx dependency service
    depends_on:
      - recommender
